### ISSUE TITLE
dbtables

### ISSUE THREAD

**Issue by white-gecko** [TamarArndt/minimalnotworkingexample#2]
> BESONDERS PROBLEMATISCH
> enthält Klassendefinitionen zu tables aus der Datenbank.
> Die Klassendefinitionen müssen so sein wie sie sind: sie benötigen Base (und engine) von DbConnection
> aber von vornherein, also man kann ihnen Base nicht im Konstruktor übergeben.
> 
> keinen blassen Schimmer, was man hier tun könnte

**Comment by white-gecko** [comment]
Dieses modul wird in deine minimal not working example aktuell nicht verwendet, kannst du da ein kleines beispiel mit einbauen, wo dieses modul gebraucht wird?

**Comment by TamarArndt** [comment]
habe die Abhängigkeiten in appstatus.datehandler eingebaut.
